version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80" # Ändere den externen Port auf 8080
    environment:
      NODE_ENV: production
    restart: always